default: &default
  adapter: postgresql
  database: gogopiao_<%= Rails.env %>
  username: postgres
  password: 111111 
  host: 127.0.0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
